name: Matrix
on: 
  push

jobs:
    node-version:
      strategy:
        os: [ubuntu-latest, windows-latest]
      max-parallel: 2
    runs:
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v1
        with: 
          node-version: 6
      - name: Log node node-version
        run: node -v
